blank_issues_enabled: false
contact_links:
  - name: Вопросы по использованию
    url: https://github.com/meowexort/pw-hub/discussions
    about: Задавайте вопросы и обсуждайте идеи в разделe Discussions.
